import type { PresentationSlide } from '../types/desktop'

type DeckOptions = {
  deckTitle: string
  sourceLabel: string
  count: number
}

const palettes = [
  ['#0e1b29', '#13334d', '#f7934f', '#d9f55f'],
  ['#170f2a', '#2b1747', '#54d2ff', '#ffe77a'],
  ['#101d1c', '#0f3a35', '#8cff98', '#d6ff78'],
  ['#211514', '#462422', '#ff9c66', '#ffd8a8'],
  ['#101828', '#19304a', '#8fdcff', '#9fe870'],
  ['#1c1122', '#3c1f4f', '#f08cff', '#7af7db'],
] as const

const sections = [
  'Introduction',
  'Workflow',
  'Performance',
  'System Map',
  'Live Status',
  'Next Step',
]

function escapeXml(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&apos;')
}

function slideSvg({
  deckTitle,
  sourceLabel,
  slideIndex,
  total,
}: {
  deckTitle: string
  sourceLabel: string
  slideIndex: number
  total: number
}): string {
  const palette = palettes[slideIndex % palettes.length]
  const [base, panel, accent, accentTwo] = palette
  const section = sections[slideIndex % sections.length]
  const title = escapeXml(deckTitle)
  const source = escapeXml(sourceLabel.toUpperCase())

  return `
    <svg xmlns="http://www.w3.org/2000/svg" width="1280" height="720" viewBox="0 0 1280 720">
      <defs>
        <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
          <stop offset="0%" stop-color="${base}" />
          <stop offset="100%" stop-color="${panel}" />
        </linearGradient>
        <radialGradient id="glowA" cx="0.2" cy="0.2" r="0.8">
          <stop offset="0%" stop-color="${accent}" stop-opacity="0.65" />
          <stop offset="100%" stop-color="${accent}" stop-opacity="0" />
        </radialGradient>
        <radialGradient id="glowB" cx="0.8" cy="0.1" r="0.8">
          <stop offset="0%" stop-color="${accentTwo}" stop-opacity="0.4" />
          <stop offset="100%" stop-color="${accentTwo}" stop-opacity="0" />
        </radialGradient>
      </defs>
      <rect width="1280" height="720" fill="url(#bg)" />
      <rect width="1280" height="720" fill="url(#glowA)" />
      <rect width="1280" height="720" fill="url(#glowB)" />
      <g stroke="rgba(255,255,255,0.08)">
        ${Array.from({ length: 16 }, (_, index) => {
          const x = index * 80
          return `<line x1="${x}" y1="0" x2="${x}" y2="720" />`
        }).join('')}
        ${Array.from({ length: 10 }, (_, index) => {
          const y = index * 80
          return `<line x1="0" y1="${y}" x2="1280" y2="${y}" />`
        }).join('')}
      </g>
      <g>
        <rect x="56" y="54" width="180" height="38" rx="19" fill="rgba(255,255,255,0.08)" stroke="${accent}" />
        <text x="146" y="79" text-anchor="middle" font-family="Avenir Next, Helvetica Neue, sans-serif" font-size="16" fill="${accent}">${source}</text>
      </g>
      <g>
        <text x="72" y="180" font-family="Avenir Next Condensed, Trebuchet MS, sans-serif" font-weight="700" font-size="72" fill="#f4f8ff">${title}</text>
        <text x="72" y="230" font-family="Avenir Next, Helvetica Neue, sans-serif" font-size="26" fill="rgba(244,248,255,0.72)">GesturePro desktop shell / Tauri GUI preview</text>
      </g>
      <g>
        <rect x="72" y="300" width="540" height="280" rx="30" fill="rgba(7,12,22,0.45)" stroke="rgba(255,255,255,0.12)" />
        <text x="104" y="356" font-family="Avenir Next, Helvetica Neue, sans-serif" font-size="20" fill="${accentTwo}">Section ${slideIndex + 1}</text>
        <text x="104" y="414" font-family="Avenir Next Condensed, Trebuchet MS, sans-serif" font-size="54" font-weight="700" fill="#ffffff">${section}</text>
        <text x="104" y="468" font-family="Avenir Next, Helvetica Neue, sans-serif" font-size="22" fill="rgba(244,248,255,0.74)">This slide is generated by the mock bridge so the Tauri GUI can be tested before the Python core is connected.</text>
        <text x="104" y="518" font-family="Avenir Next, Helvetica Neue, sans-serif" font-size="22" fill="rgba(244,248,255,0.74)">Navigation, HUD, session panels, and load states already mirror the future desktop runtime.</text>
      </g>
      <g>
        <rect x="714" y="154" width="486" height="426" rx="34" fill="rgba(5,10,18,0.52)" stroke="rgba(255,255,255,0.14)" />
        <circle cx="822" cy="274" r="76" fill="rgba(255,255,255,0.05)" stroke="${accent}" stroke-width="3" />
        <circle cx="1042" cy="412" r="126" fill="rgba(255,255,255,0.04)" stroke="${accentTwo}" stroke-width="2" />
        <rect x="770" y="506" width="374" height="18" rx="9" fill="rgba(255,255,255,0.08)" />
        <rect x="770" y="506" width="${Math.max(70, (slideIndex + 1) * 60)}" height="18" rx="9" fill="${accent}" />
        <text x="770" y="220" font-family="Avenir Next, Helvetica Neue, sans-serif" font-size="19" fill="rgba(244,248,255,0.68)">Current focus</text>
        <text x="770" y="258" font-family="Avenir Next Condensed, Trebuchet MS, sans-serif" font-size="44" font-weight="700" fill="#ffffff">Bridge-ready UI states</text>
        <text x="770" y="318" font-family="Avenir Next, Helvetica Neue, sans-serif" font-size="20" fill="rgba(244,248,255,0.74)">• fake gesture events</text>
        <text x="770" y="356" font-family="Avenir Next, Helvetica Neue, sans-serif" font-size="20" fill="rgba(244,248,255,0.74)">• fake session PIN / phone sync</text>
        <text x="770" y="394" font-family="Avenir Next, Helvetica Neue, sans-serif" font-size="20" fill="rgba(244,248,255,0.74)">• local file metadata flow</text>
        <text x="770" y="432" font-family="Avenir Next, Helvetica Neue, sans-serif" font-size="20" fill="rgba(244,248,255,0.74)">• slide viewer + HUD behavior</text>
      </g>
      <g>
        <text x="72" y="660" font-family="Avenir Next, Helvetica Neue, sans-serif" font-size="18" fill="rgba(244,248,255,0.56)">Mock slide ${slideIndex + 1} / ${total}</text>
        <text x="1200" y="660" text-anchor="end" font-family="Avenir Next, Helvetica Neue, sans-serif" font-size="18" fill="rgba(244,248,255,0.56)">GesturePro Desktop</text>
      </g>
    </svg>
  `
}

function toDataUrl(svg: string): string {
  return `data:image/svg+xml;charset=UTF-8,${encodeURIComponent(svg)}`
}

function createDeck({ deckTitle, sourceLabel, count }: DeckOptions): PresentationSlide[] {
  return Array.from({ length: count }, (_, index) => ({
    id: `${deckTitle.toLowerCase().replaceAll(/\s+/g, '-')}-${index + 1}`,
    title: `${deckTitle} / ${sections[index % sections.length]}`,
    imageUrl: toDataUrl(
      slideSvg({
        deckTitle,
        sourceLabel,
        slideIndex: index,
        total: count,
      }),
    ),
  }))
}

export function createDemoDeck(): PresentationSlide[] {
  return createDeck({
    deckTitle: 'Demo Deck',
    sourceLabel: 'demo',
    count: 5,
  })
}

export function createLocalDeck(fileName: string): PresentationSlide[] {
  const deckTitle = fileName.replace(/\.[^.]+$/, '') || 'Local Presentation'
  return createDeck({
    deckTitle,
    sourceLabel: 'file',
    count: 6,
  })
}

export function createRemoteDeck(): PresentationSlide[] {
  return createDeck({
    deckTitle: 'Mobile Sync Deck',
    sourceLabel: 'remote',
    count: 4,
  })
}
